### PR TITLE
Add docker compose support

### PR DESCRIPTION
**Pull request by puhoshville**
Run this project locally using simple `docker-compose up` command

### CODE REVIEW

**Comment by drahoslove** [comment]
Hi, thank you for the pull request, it is excellent!

Just have a question. What the reason is for removing the lock files? Isn't it an anti-pattern?

~Also, I don't actually use the `main-bundle.js` so the frontend bundling is not even necessary.
It was just some test and I forgot to remove it - I decided to use just the native JavaScript modules, for easier development.~

~Using Webpack would increase the compatibility with older browsers, but I think those which don't support modules also don't support the WebAudio and WebMidi APIs, so I don't see a point.~

Edit: now I see you don't actually run the npm build. Sorry, you can ignore that :)

**Comment by puhoshville** [comment]
@drahoslove rebased on top of current main branch and package-lock restored.
just want to notice following: for frontend and backend the same docker image is used. so I moved specific for backend requirements ("jsonwebtoken" and "node-fetch") into package.json from root folder.

**Comment by drahoslove** [comment]
Was that necessary?
I'm not too familiar with docker, so maybe I'm completely wrong, but I think you should be able to use same Dockerfile for different package.json

maybe like this?
```yml
version: '3'
services:
  frontend:
    ports:
      - "80:80"
    build:
      context: ./
      dockerfile: Dockerfile
  backend:
    ports:
      - "11088:11088"
    build:
      context: ./backend
      dockerfile: ../Dockerfile
```

Also why there are two COPY in the docker file?
Wouldn't this be sufficient enough?

```Dockerfile
FROM node:14-alpine
WORKDIR /app
COPY . .
RUN npm install
CMD ["npm", "run", "start"]

**Comment by puhoshville** [comment]
```
      context: ./backend
```
We can't use this context since backend refers to source files from upper level (from root folder). But check pls new implementation with different Dockerfile for backend.


`Also why there are two COPY in the docker file?`
A separate COPY for the requirements and for all other files optimizes the image building process. Otherwise docker will download node_modules every time any of files have been modified.

**Comment by drahoslove** [comment]
Which upper-level files do you mean? 
If it is only this line `const MIDI_CACHE_DIR = '../audio/midi'` inside `backend/autoplay.js` we could change it to `./midi-cache` - it is not used by the frontend anyway.

But your current solution looks good too 👍
(We only should add a second `npm install` for the backend to the readme)

I didn't know COPY has that feature, that's cool :)

**Comment by puhoshville** [comment]
@drahoslove check it pls)

**Review by drahoslove — APPROVED** [review]
It looks good now. Thank you!

**Pull request merged**
