### PR TITLE
Increase room number

### PR DESCRIPTION
**Pull request by DanZalov**
List of changes:

- backend database reorganized from arrays to objects to improve flexibility
- room number limit increased, coded by letters
- room enter interface changed (focused on features like entering a specific room, finding empty or staying in private)
- fixed bouncing links while modal opening

### CODE REVIEW

**Comment by drahoslove** [comment]
This is really good PR, especially the backend changes, thank you.
I wonder how you managed to navigate in my messy code so well. You have my appreciation 👍

It's a good idea to simplify the room selection. And to allow for a larger number of rooms.
I like the "find random empty room" feature.

Some problems, however:

1) I'd like to preserve the possibility of easily accessing the default main room (gid: 0) - there is no obvious way to do that now.
2) does the "enter room hash" modal makes sense? You'll usually just click the link someone sent you. And you can always just edit the URL in the address bar, right? So what is the reason behind it?
3) I don't like the icons, especially the seat-recline-extra - Not a big deal, however.
4) Is it obvious, that "private room" means "offline room just for you"? 🤔 Two people can have privacy in the custom room.
5) "empty room" is more like a command, not actually a room (cannot be selected) so it should have different design
6) it is not clear where the numbers `141167095653375/6` come from.
Could you use a named constant, for example, `const MAX_HASHABLE_INT = 26**10 - 1` ?

My proposal on how to change the room "tabs"

1) static tab labeled either `main room`, `global room` or `public room`, gid: 0 - we can use `mid-globe` as icon for example
2) static tab labeled `offline mode` or `incognito mode` gid: -1 - it can have the `mid-incognito` icon (but I might change it to something nicer later)
3) static button `new empty room` as the last item, with icon `mdi-plus-thick`- it should have `background: transparent; box-shadow: none;` to distinguish it from the selectable tabs
4) dynamic list of custom rooms tabs (gid > 0), which were created/visited by the user
   - with this, you can easily return back to the room you just left
   - we can use some of the `mdi-numeric-` or `mdi-alpha-` icons for those (the number/letter in the icon will be either index or derived from the room hash)
   - not sure whether the list should be placed between main and incognito tabs, or between the incognito tab and the plus button
   - this list could be limited to some small number, so it won't grow indefinitely when clicking the plus button (either the plus will disappear when the limit is reached, or the oldest/left-most room will be removed)
   - the list might be preserved in `localStorage`, so it won't be lost on refresh - in that case, it would probably be nice to add an option to remove a room from the list

What do you think?

I can implement that by myself.

I changed the destination branch from `master` to `dev`.
That way I can merge this PR and implement the changes without deploying it (the frontend is hosted on GitHub Pages, automatically deployed from the master branch).

~~Also, for the rooms with gid > 255, the sound from other players does not actually play.
It is  probably because the gid and uid values are being sent with each action inside of Uint8Array - so the values are truncated to fit in 8 bits https://github.com/drahoslove/pianco/blob/master/js/io.js#L374
and are checked on arrival https://github.com/drahoslove/pianco/blob/master/js/io.js#L224-L227
This check is probably not necessary, since the messages are filtered on backend. -> Let me fix that.~~ -> Fixed

**Comment by DanZalov** [comment]
Thank you for your feedback!
I agree, frontend is a tricky part here. Let's discuss!

Problems:
1. Well, of course we can leave it there, but I don't think users need it.. I thought we shouldn't focus on specific rooms.
2. I just think editing hash in modal is more a user-friendly way. I agree it duplicates functionality, but it isn't obvious that user can just edit the URL to change a room. Personally, I had no idea) Firstly, I wanted to put a room indicator, but with hash it would be space consuming. So I left the room change modal with an indicator instead.
3. I don't insist on them, we could choose something better
4. That's a good one! Well, it isn't obvious.. I just feel that "isolation" word has a negative connotation. "Solitude" is better but I've used "private". We have linguistic issues) That's why I choose "incognito" icon. Like no one can hear you. Maybe it's all nonsense, you tell me)
5. Totally agree! 
6. My bad. I should've replaced by a constant, agree. 

I like your proposals 1-3: 'main room', 'offline mode' and 'new empty room'. 
4 proposal: 
- I think it is a good idea to save a room number people randomly chose by 'new empty room'. If they want to continue, they wouldn't have to choose a new one, share number. We saved it for them.
- Well, wouldn't it be space consuming to use large numbers or hash? We will have like two saved rooms that way..
- I personally like it being between main and incognito tabs
- Agree. I'd prefer disabling button. It is a good interface!
- We could open a modal onclick: 'enter' or 'delete' room. But it doesn't feel right.. Or we could add another button for removing saved rooms. It would show the list, and user will choose what room to remove. And it appears if user have saved rooms.
So, there is a question left about modal for editing hash. Do you still feel it excessive?

I don't mind if you implement changes. You definitely feel the app's style better :)

**Comment by drahoslove** [comment]
Great. I'm glad you mostly agree :)

- _Well, wouldn't it be space consuming to use large numbers or hash? We will have like two saved rooms that way._ - Not sure you understand me - I meant to use a single icon - for example if the hash of the room starts with letter 'b', the icon could be `mdi-circle-b`, or something like that. I'll just try something and will see what works well.
- _I'd prefer disabling button._ - yes, disabling is better than hiding 👍 
- the tab of custom room which is empty could have a little (×) button for closing, which could appear on mouse hover, like this: 
image
(I know the hover feature It's not ideal for mobile devices, but I'd like to change the UI for those devices anyway, because currently it is too much cluttered on the smaller screens and you could easily accidentally switch the room when shifting octaves. So I'll probably hide all the tabs under a single button which would open a list of rooms in a modal window, for small devices.)

_So, there is a question left about modal for editing hash. Do you still feel it excessive?_
I mainly just still don't understand what's the use case for it.
Could you describe when would you need to enter the hash manually?
 - Either you create a new room, in which case you don't care about the letters, and you'll just copy and share the URL to whoever you want to share it with.  (It would make more sense to implement some `share link` button, which would copy the URL to your clipboard - that might be helpful for phones, where the URL copying is a bit more annoying)
  - Or you are the other person, who just received the URL from someone, in which case you just click the link.

 - Or you might not want to / be able to send the link, because you are with the person either on a phone call or meeting in person - in those situations you'll probably be dictating the whole address anyway.
 What I could do to make that easier, is remove the `#`, so the URL would be just `pian.co/xxx-xxxx-xxx` - that's a bit easier to read and to type.
 Btw, the dashes are for better readability? I think those could be removed too. And we could make the string a bit shorter as well, eg. 8 of base32 characters - that's still plenty of possible values to ensure privacy.

To me, the modal for entering the room name would make sense if you could enter arbitrary letters to name the room using words. (This might be an interesting idea for the future, but I'd rather keep it simple for now.)

**Comment by DanZalov** [comment]
- Interesting idea about letter icons, but they could duplicate.. Or just use numbers like now? Yeah, looks like we have to try some options and see
- This is a nice (×) button design! I love it) Agree about small devices
- That's it! 'Share link' is an ultimate solution to do it user-friendly way, from my point of view)

Looks like we've come to an agreement :)

**Pull request merged**
